# country_data.py

COUNTRY_PHONE_DATA = {
    'US': {'code': b'+1 ', 'prefixes': [b'201',b'202',b'212',b'213',b'310',b'415',b'646',b'718',b'917'], 'length':7},
    'NL': {'code': b'+31 ', 'prefixes': [b'6'], 'length':8},
    'GB': {'code': b'+44 ', 'prefixes': [b'7'], 'length':9},
    'DE': {'code': b'+49 ', 'prefixes': [b'15',b'16',b'17'], 'length':8},
    'FR': {'code': b'+33 ', 'prefixes': [b'6',b'7'], 'length':8},
    'IN': {'code': b'+91 ', 'prefixes': [b'9',b'8',b'7',b'6'], 'length':9},
    'BR': {'code': b'+55 ', 'prefixes': [b'9',b'8',b'7'], 'length':8},
    'AU': {'code': b'+61 ', 'prefixes': [b'4'], 'length':8},
    'CA': {'code': b'+1 ', 'prefixes': [b'204',b'236',b'250',b'289',b'306',b'343',b'365',b'403',b'416',b'418'], 'length':7},
    'ZA': {'code': b'+27 ', 'prefixes': [b'6',b'7',b'8'], 'length':7},
    'RU': {'code': b'+7 ', 'prefixes': [b'9'], 'length':9},
    'MX': {'code': b'+52 ', 'prefixes': [b'55',b'56',b'33'], 'length':7},
    'JP': {'code': b'+81 ', 'prefixes': [b'70',b'80',b'90'], 'length':8},
    'KR': {'code': b'+82 ', 'prefixes': [b'10'], 'length':8},
    'IT': {'code': b'+39 ', 'prefixes': [b'3'], 'length':9},
    'ES': {'code': b'+34 ', 'prefixes': [b'6',b'7'], 'length':8},
    'SE': {'code': b'+46 ', 'prefixes': [b'7'], 'length':8},
    'NO': {'code': b'+47 ', 'prefixes': [b'4',b'9'], 'length':7},
    'FI': {'code': b'+358 ', 'prefixes': [b'4',b'5'], 'length':7},
    'PL': {'code': b'+48 ', 'prefixes': [b'5',b'6',b'7'], 'length':7},
    'BE': {'code': b'+32 ', 'prefixes': [b'4'], 'length':8},
    'AT': {'code': b'+43 ', 'prefixes': [b'6'], 'length':7},
    'CH': {'code': b'+41 ', 'prefixes': [b'7'], 'length':7},
    'IE': {'code': b'+353 ', 'prefixes': [b'8',b'9'], 'length':7},
    'NZ': {'code': b'+64 ', 'prefixes': [b'2',b'21',b'22',b'27'], 'length':6},
    'SG': {'code': b'+65 ', 'prefixes': [b'8',b'9'], 'length':7},
    'MY': {'code': b'+60 ', 'prefixes': [b'1'], 'length':8},
    'TH': {'code': b'+66 ', 'prefixes': [b'8',b'9'], 'length':7},
    'PH': {'code': b'+63 ', 'prefixes': [b'9'], 'length':9},
    'AR': {'code': b'+54 ', 'prefixes': [b'9'], 'length':8},
    'CL': {'code': b'+56 ', 'prefixes': [b'9'], 'length':8},
    'CO': {'code': b'+57 ', 'prefixes': [b'3',b'5'], 'length':7},
    'EG': {'code': b'+20 ', 'prefixes': [b'10',b'11'], 'length':8},
    'UA': {'code': b'+380 ', 'prefixes': [b'50',b'67',b'96',b'97'], 'length':7},
    'IL': {'code': b'+972 ', 'prefixes': [b'50',b'52',b'54',b'55'], 'length':7},
    'TR': {'code': b'+90 ', 'prefixes': [b'5'], 'length':9},
    'SA': {'code': b'+966 ', 'prefixes': [b'5'], 'length':8},
    'AE': {'code': b'+971 ', 'prefixes': [b'50',b'55',b'56'], 'length':7},
    'ID': {'code': b'+62 ', 'prefixes': [b'8'], 'length':8},
    'VN': {'code': b'+84 ', 'prefixes': [b'9'], 'length':8},
    'PK': {'code': b'+92 ', 'prefixes': [b'3'], 'length':9},
    'NG': {'code': b'+234 ', 'prefixes': [b'7',b'8',b'9'], 'length':7},
    'KE': {'code': b'+254 ', 'prefixes': [b'7'], 'length':7},
}
