# Global landline phone data (with real data where available)

LANDLINE_PHONE_DATA = {
    'AD': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AQ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AT': {'code': b'+43 ', 'prefixes': [b'1', b'316', b'662'], 'length': 7},
    'AU': {'code': b'+61 ', 'prefixes': [b'2', b'3', b'7', b'8'], 'length': 8},
    'AW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AX': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'AZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BB': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BD': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BE': {'code': b'+32 ', 'prefixes': [b'2', b'3', b'4', b'9'], 'length': 7},
    'BF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BJ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BQ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BV': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'BZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CA': {'code': b'+1 ', 'prefixes': [b'416', b'514', b'604', b'780'], 'length': 7},
    'CC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CD': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CH': {'code': b'+41 ', 'prefixes': [b'21', b'31', b'41', b'61'], 'length': 7},
    'CI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CV': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CX': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'CZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'DE': {'code': b'+49 ', 'prefixes': [b'30', b'40', b'69', b'89'], 'length': 7},
    'DJ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'DK': {'code': b'+45 ', 'prefixes': [b'32', b'33', b'35'], 'length': 8},
    'DM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'DO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'DZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'EC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'EE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'EG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'EH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ER': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ES': {'code': b'+34 ', 'prefixes': [b'91', b'93', b'96'], 'length': 7},
    'ET': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'FI': {'code': b'+358 ', 'prefixes': [b'9', b'2', b'3'], 'length': 7},
    'FJ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'FK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'FM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'FO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'FR': {'code': b'+33 ', 'prefixes': [b'1', b'2', b'3', b'4', b'5'], 'length': 8},
    'GA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GB': {'code': b'+44 ', 'prefixes': [b'20', b'121', b'131', b'161'], 'length': 8},
    'GD': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GP': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GQ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'GY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'HK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'HM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'HN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'HR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'HT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'HU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ID': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'IE': {'code': b'+353 ', 'prefixes': [b'1', b'21', b'61'], 'length': 7},
    'IL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'IM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'IN': {'code': b'+91 ', 'prefixes': [b'11', b'22', b'33', b'44'], 'length': 8},
    'IO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'IQ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'IR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'IS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'IT': {'code': b'+39 ', 'prefixes': [b'06', b'02', b'011', b'081'], 'length': 7},
    'JE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'JM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'JO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'JP': {'code': b'+81 ', 'prefixes': [b'3', b'6', b'45'], 'length': 8},
    'KE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KP': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'KZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LB': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LV': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'LY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MD': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ME': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ML': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MP': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MQ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MV': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MX': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'MZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NL': {'code': b'+31 ', 'prefixes': [b'10', b'20', b'30', b'50'], 'length': 7},
    'NO': {'code': b'+47 ', 'prefixes': [b'2', b'3', b'5'], 'length': 7},
    'NP': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'NZ': {'code': b'+64 ', 'prefixes': [b'3', b'4', b'6', b'7', b'9'], 'length': 7},
    'OM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'PY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'QA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'RE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'RO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'RS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'RU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'RW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SB': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SD': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SE': {'code': b'+46 ', 'prefixes': [b'8', b'31', b'40'], 'length': 7},
    'SG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SJ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ST': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SV': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SX': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'SZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TD': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TH': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TJ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TK': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TL': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TO': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TR': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TV': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'TZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'UA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'UG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'UM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'US': {'code': b'+1 ', 'prefixes': [b'212', b'213', b'312', b'415', b'617'], 'length': 7},
    'UY': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'UZ': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'VA': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'VC': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'VE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'VG': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'VI': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'VN': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'VU': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'WF': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'WS': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'YE': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'YT': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ZA': {'code': b'+27 ', 'prefixes': [b'11', b'21', b'31'], 'length': 7},
    'ZM': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
    'ZW': {'code': b'+999 ', 'prefixes': [b'1'], 'length': 7},
}
